# Generated by Django 4.2.10 on 2024-02-11 14:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_category_product_quantity_alter_product_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(5)], verbose_name='Рейтинг'),
        ),
    ]
