[program:reactapi]
command=/root/projects/react_api/venv/bin/gunicorn core.wsgi:application -c /root/projects/react_api/server/gunicorn.conf.py
directory=/root/projects/react_api
user=root
autorestart=true
redirect_stderr=true
stdout_logfile=/root/projects/react_api/logs/debug.log